# -*- coding: utf-8 -*-

# Non-failing inspection of objects.  The inspection is {Lookout::Encode
# encoded} for output.
class Lookout::Inspect
  # @param [Object] object The object to inspect
  # @param [String] type A description of the type of object being inspected
  def initialize(object, type)
    @object, @type = object, type
  end

  # @return [String] An UTF-8-encoded String inspection of the given object,
  #   generated by invoking #inspect on it, then {Lookout::Encode encoding} it
  #   as UTF-8, using #dump if any transcoding that may take place fails
  def call
    Lookout::Encode.new(inspection = inspect_object).call
  rescue => e
    '(cannot encode inspected %s for output: %s; %s)' %
      [@type,
       Lookout::Exception.new(e).message,
       begin
         'dumping instead: %s' % [inspection.dump]
       rescue => inner
         'dumping also failed: %s' % Lookout::Exception.new(inner).message
       end]
  end

  private

  def inspect_object
    String(@object.inspect)
  rescue => e
    '(cannot inspect %s: %s)' % [@type, Lookout::Exception.new(e).message]
  end
end
