# -*- coding: utf-8 -*-

module Lookout
  Version = '2.4.0'

  class << Version
    def content
      {
        :requires => %w'
          stringio
        ',
        :loads => %w'
          lookout/object.rb
          lookout/aphonic.rb
          lookout/diff.rb
          lookout/diff/range.rb
          lookout/diff/algorithms.rb
          lookout/diff/algorithms/difflib.rb
          lookout/diff/algorithms/difflib/position.rb
          lookout/diff/algorithms/difflib/position/to.rb
          lookout/diff/formats.rb
          lookout/diff/formats/inline.rb
          lookout/diff/formats/set.rb
          lookout/diff/formats/unified.rb
          lookout/diff/group.rb
          lookout/diff/groups.rb
          lookout/diff/match.rb
          lookout/diff/operation.rb
          lookout/diff/operations.rb
          lookout/diff/operations/delete.rb
          lookout/diff/operations/equal.rb
          lookout/diff/operations/insert.rb
          lookout/diff/operations/replace.rb
          lookout/expect.rb
          lookout/expect/object.rb
          lookout/expect/object/context.rb
          lookout/expect/classes.rb
          lookout/expect/classes/exception.rb
          lookout/expect/output.rb
          lookout/expect/reception.rb
          lookout/expect/exception.rb
          lookout/expect/state.rb
          lookout/expect/warning.rb
          lookout/expected.rb
          lookout/expected/object.rb
          lookout/expected/array.rb
          lookout/expected/classes.rb
          lookout/expected/classes/exception.rb
          lookout/expected/exception.rb
          lookout/expected/falseclass.rb
          lookout/expected/hash.rb
          lookout/expected/module.rb
          lookout/expected/range.rb
          lookout/expected/reception.rb
          lookout/expected/regexp.rb
          lookout/expected/output.rb
          lookout/expected/state.rb
          lookout/expected/string.rb
          lookout/expected/trueclass.rb
          lookout/expected/warning.rb
          lookout/expectations.rb
          lookout/expectations/context.rb
          lookout/expectations/line.rb
          lookout/inspect.rb
          lookout/inspect/actual.rb
          lookout/inspect/argument.rb
          lookout/inspect/error.rb
          lookout/inspect/expected.rb
          lookout/output.rb
          lookout/reception.rb
          lookout/stub.rb
          lookout/stub/method.rb
          lookout/stub/method/defined.rb
          lookout/stub/method/undefined.rb
          lookout/stub/methods.rb
          lookout/stub/object.rb
          lookout/mock.rb
          lookout/mock/method.rb
          lookout/mock/method/arguments.rb
          lookout/mock/method/arguments/any.rb
          lookout/mock/method/arguments/list.rb
          lookout/mock/method/arguments/none.rb
          lookout/mock/method/calls.rb
          lookout/mock/method/calls/exactly.rb
          lookout/mock/method/calls/lower.rb
          lookout/mock/method/calls/upper.rb
          lookout/mock/method/defined.rb
          lookout/mock/method/undefined.rb
          lookout/mock/methods.rb
          lookout/mock/object.rb
          lookout/object/not.rb
          lookout/object/not/receive.rb
          lookout/object/to.rb
          lookout/object/to/receive.rb
          lookout/state.rb
          lookout/state/recording.rb
          lookout/state/verify.rb
          lookout/state/be.rb
          lookout/state/have.rb
          lookout/state/not.rb
          lookout/state/not/verify.rb
          lookout/state/not/be.rb
          lookout/state/not/have.rb
          lookout/result.rb
          lookout/results.rb
          lookout/results/error.rb
          lookout/results/error/exception.rb
          lookout/results/error/exception/backtrace.rb
          lookout/results/failure.rb
          lookout/results/failures.rb
          lookout/results/failures/behavior.rb
          lookout/results/failures/state.rb
          lookout/results/fulfilled.rb
          lookout/results/trackers.rb
          lookout/results/trackers/failure.rb
          lookout/results/unsuccessful.rb
          lookout/ui.rb
          lookout/ui/console.rb
          lookout/warning.rb
        ',
        :manual => %w'
          lookout/version.rb
        '
      }
    end
  end
end
